package com.taskforge.common.constant;

public enum ActivityType {
    USER_REGISTERED,
    USER_LOGGED_IN,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_RESTORED,
    MEMBER_INVITED,
    MEMBER_JOINED,
    MEMBER_REMOVED,
    OWNERSHIP_TRANSFERRED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    TASK_DELETED,
    COMMENT_ADDED,
    ATTACHMENT_UPLOADED
}
